services:
  backend:
    image: ${DOCKER_REGISTRY-}api:1.0.0
    build:
      context: .
      dockerfile: Web3D.API/Dockerfile
    depends_on:
      - postgres_db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  client:
    image: client:1.0.0
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ["npm", "run", "dev"]

  postgres_db:
    container_name: postgres
    image: postgres:14.1
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=web3ddb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres-data: